### ISSUE TITLE
Build issue against OpenSSL 1.1.1

### ISSUE THREAD

**Issue by Lynx098** [smuellerDD/acvpparser#47]
Hi, @smuellerDD.

Is there any way to build acvp-parser against OpenSSL 1.1.1?

I'd like to evaluate implementations of some algorithms in OpenSSL 1.1.1.
But I've encountered a build issue with "make openssl" command.

> gcc -Wextra -Wall -pedantic -fPIE -O2 -Wno-long-long -Werror -DACVP_PARSER_IUT="openssl" -g -std=c11 -DUBUNTU -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fwrapv --param ssp-buffer-size=4 -Iparser -c -o backends/backend_openssl_common.o backends/backend_openssl_common.c
In file included from backends/backend_openssl_common.c:24:
backends/backend_openssl_common.h:61:10: fatal error: openssl/fips.h: No such file or directory

Reading the issue #16, I assumed that acvp-parser can work with OpenSSL 1.1.x.
> Fipsified OpenSSL 1.0.x, 1.1.x and OpenSSL 2.0.x should work.

Does this means, building acvp-parser requires fipsified OpenSSL 1.1.1?
If so, please tell me where it is.

Thanks.

**Comment by smuellerDD** [comment]
Am Dienstag, 7. Dezember 2021, 09:51:17 CET schrieb Lynx098:

Hi Lynx098,

> Hi, @smuellerDD.
> 
> Is there any way to build acvp-parser against OpenSSL 1.1.1?
> 
> I'd like to evaluate implementations of some algorithms in OpenSSL 1.1.1.
> But I've encountered a build issue with "make openssl" command.
> 
> > gcc -Wextra -Wall -pedantic -fPIE -O2 -Wno-long-long -Werror
> > -DACVP_PARSER_IUT="openssl" -g -std=c11 -DUBUNTU -D_FORTIFY_SOURCE=2
> > -fstack-protector-strong -fwrapv --param ssp-buffer-size=4 -Iparser -c -o
> > backends/backend_openssl_common.o backends/backend_openssl_common.c
> In file included from backends/backend_openssl_common.c:24:
> backends/backend_openssl_common.h:61:10: fatal error: openssl/fips.h: No
> such file or directory
> 
> Reading the issue #16, I assumed that acvp-parser can work with OpenSSL
> 1.1.x.
> > Fipsified OpenSSL 1.0.x, 1.1.x and OpenSSL 2.0.x should work.
> 
> Does this means, building acvp-parser requires fipsified OpenSSL 1.1.1?
> If so, please tell me where it is.

Sure, only the fipsified OpenSSL provides the algorithm implementations that 
are consistent with the NIST requirements.
> 
> Thanks.


Ciao
Stephan

**Comment by Lynx098** [comment]
Hi, @smuellerDD 
Thank you for replying.

> Sure, only the fipsified OpenSSL provides the algorithm implementations that are consistent with the NIST requirements.

I've understood.

Do you know how to get the fipsified OpenSSL 1.1.1?

Thanks.
Lynx098

**Comment by smuellerDD** [comment]
Am Dienstag, 7. Dezember 2021, 14:25:41 CET schrieb Lynx098:

Hi Lynx098,

> Hi, @smuellerDD
> Thank you for replying.
> 
> > Sure, only the fipsified OpenSSL provides the algorithm implementations
> > that are consistent with the NIST requirements.
> I've understood.
> 
> Do you know how to get the fipsified OpenSSL 1.1.1?

See the Centos/RHEL/Fedora/SLES OpenSSL version.
> 
> Thanks.
> Lynx098


Ciao
Stephan

**Comment by Lynx098** [comment]
Hi, @smuellerDD 

> See the Centos/RHEL/Fedora/SLES OpenSSL version.

Ah, I see now.
I tried to build the codes that downloaded from the official website, so I wasn't able to build acvp-parser against OpenSSL. 

My question has been resolved.  I will close this issue.

Thanks you, smuellerDD.
Lynx098
