### ISSUE TITLE
Compiling with openssl 1.1.1 gives error of fips.h not found

### ISSUE THREAD

**Issue by sbrahul** [smuellerDD/acvpparser#58]
Hi,

I was trying to compile with openssl 1.1.1. This version doesnt have fips canister support (1.0.2 and 3.x has). Due to this, I am getting an error:

```
In file included from backends/backend_openssl_common.c:24:
backends/backend_openssl_common.h:62:10: fatal error: openssl/fips.h: No such file or directory

```

Does this mean that openssl 1.1.1 is not supported for the parser?
